services:
  postgres-general:
    image: postgres:16
    container_name: postgres-general
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: phototours_db
    ports:
      - "5432:5432"
    volumes:
      - phototours_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10

  pt-general:
    build:
      context: .
      dockerfile: pt-general/Dockerfile
    container_name: pt-general
    restart: unless-stopped
    depends_on:
      postgres-general:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://root:secret@postgres-general:5432/phototours_db?schema=public
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: sh -c "pnpm prisma migrate deploy && pnpm start"

volumes:
  phototours_postgres_data: