services:
  postgres-general:
    build:
      context: .
      dockerfile: ./postgres/postgres-general.Dockerfile
    container_name: postgres-pt-general
    ports:
      - "5432:5432"
    env_file:
      - ./pt-general/.env
    volumes:
      - postgres-general:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d phototours_db -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 20

  pt-general-go:
    build:
      context: ./pt-general-go
      dockerfile: Dockerfile
    container_name: pt-general-go
    env_file:
      - ./pt-general-go/.env
    networks:
      - app-network
    ports:
      - "8000:8000"
    depends_on:
      postgres-general:
        condition: service_healthy

  # pt-general:
  #   build:
  #     context: .
  #     dockerfile: pt-general/Dockerfile
  #   container_name: pt-general
  #   env_file:
  #     - ./pt-general/.env
  #   networks:
  #     - app-network
  #   expose:
  #     - "8000"
  #   depends_on:
  #     postgres-general:
  #       condition: service_healthy

  pt-web:
    build:
      context: .
      dockerfile: pt-web/Dockerfile
    container_name: pt-web
    env_file:
      - ./pt-web/.env
    expose:
      - "5174:5174"
    networks:
      - app-network

  gateway:
    image: nginx:1.24.0-alpine
    container_name: gateway
    ports:
      - "5173:80"
    volumes:
      - ./gateway/local.docker.nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    depends_on:
      - pt-general-go
      - pt-web

  # grafana:
  #   build:
  #     context: .
  #     dockerfile: ./grafana/Dockerfile
  #   container_name: grafana
  #   ports:
  #     - "9876:3000"
  #   env_file:
  #     - ./grafana/.env
  #   networks:
  #     - app-network

volumes:
  postgres-general:
  # grafana-data:

networks:
  app-network:
    driver: bridge
